name: DangerJS - buzz-frontend
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - assigned
      - labeled
      - review_requested
  issue_comment:
    types:
      - created
      - edited
env:
  APP_NAME: buzz-frontend
  HOME: /actions-runner/_work
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
  AWS_DEFAULT_REGION: ap-south-1
  AWS_S3_STAGE_CACHE_BUCKET_NAME: rzp-1018-nonprod-actions-cache
  AWS_S3_STAGE_ROLE: arn:aws:iam::101860328116:role/gha-stage-buzz-frontend-action
jobs:
  danger-js:
    name: Run DangerJS
    runs-on: self-hosted
    if: ${{ github.event_name == 'pull_request' }}
    timeout-minutes: 10
    concurrency:
      group: danger-js-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_BOT_TOKEN }}
      - name: Setup Node v18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - name: Install Yarn
        run: npm install -g yarn
      - name: Setup Cache & Install Dependencies
        uses: bahmutov/npm-install@v1.8.15
        with:
          install-command: yarn --frozen-lockfile
      - name: Danger JS
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_DISABLE_TRANSPILATION: "true"
  danger-js-performance:
    name: Run DangerJS Performance
    runs-on: self-hosted
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, format('https://buzz-frontend-pr-{0}.dev.razorpay.in', github.event.issue.number))}}
    timeout-minutes: 30
    concurrency:
      group: danger-js-performance-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Configure Stage AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ env.AWS_S3_STAGE_ROLE }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-duration-seconds: 900
      - name: Checkout Codebase
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_BOT_TOKEN }}
      - name: Setup Node v18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - name: Install Yarn
        run: npm install -g yarn
      - name: Setup Cache & Install Dependencies
        uses: bahmutov/npm-install@v1.8.15
        with:
          install-command: yarn --frozen-lockfile
      - name: Install chrome dependencies
        run: apt-get -y install ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
      - name: Install Latest Chrome
        uses: browser-actions/setup-chrome@latest
      - name: Set Chrome Path
        id: set-chrome-path
        run: echo "::set-output name=CHROME_EXECUTABLE_PATH::$(which chrome)"
      - name: Danger JS
        run: yarn danger ci --dangerfile dangerfile.performance.js --id buzz-frontend-Danger_Performance
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_DISABLE_TRANSPILATION: "true"
          CHROME_EXECUTABLE_PATH: ${{ steps.set-chrome-path.outputs.CHROME_EXECUTABLE_PATH }}
          STAGE: beta
