name: Create NGINX Proxy for Devstack - buzz-frontend
on:
  push:
    paths:
      - devstack/**
env:
  APP_NAME: buzz-frontend
  HOME: /actions-runner/_work
  DOCKER_USERNAME: ${{ secrets.HARBOR_DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
  DOCKER_REGISTRY: c.rzp.io
jobs:
  nginx-proxy:
    runs-on: self-hosted
    timeout-minutes: 20
    name: Create NGINX docker image
    steps:
      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker Image
        id: build-docker-image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{env.DOCKER_REGISTRY}}/razorpay/${{env.APP_NAME}}:nginx
          push: true
          file: ./devstack/Dockerfile
