name: Version
on:
  push:
    branches:
      - master
env:
  APP_NAME: buzz-frontend
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
  HOME: /actions-runner/_work
jobs:
  version:
    name: Version Update
    if: ${{ github.event.head_commit.author.name != 'rzpcibot'}}
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_BOT_TOKEN }}
      - name: Setup Node v18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - name: Update Version
        run: |
          git config user.email "tools+cibot@razorpay.com"
          git config user.name "rzpcibot"
          npm version patch --no-commit-hooks -m "build: update version to ${APP_NAME}@%s"
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          git push
      - name: Create & Push Tag
        run: |
          git tag ${APP_NAME}@${VERSION}
          git push origin ${APP_NAME}@${VERSION}
